export const FRIEND_GET_SUCCESS = 'FRIEND_GET_SUCCESS';
export const MESSAGE_GET_SUCCESS = 'MESSAGE_GET_SUCCESS';
export const MESSAGE_SEND_SUCCESS = 'MESSAGE_SEND_SUCCESS';
export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
export const UPDATE_FRIEND_MESSAGE = 'UPDATE_FRIEND_MESSAGE';
export const MESSAGE_SEND_SUCCESS_CLEAR = 'MESSAGE_SEND_SUCCESS_CLEAR';
export const SEEN_MESSAGE = 'SEEN_MESSAGE';
export const DELIVARED_MESSAGE = 'DELIVARED_MESSAGE';
export const UPDATE = 'UPDATE';
export const MESSAGE_GET_SUCCESS_CLEAR = 'MESSAGE_GET_SUCCESS_CLEAR';
export const SEEN_ALL = 'SEEN_ALL';
export const THEME_GET_SUCCESS = 'THEME_GET_SUCCESS';
export const THEME_SET_SUCCESS = 'THEME_SET_SUCCESS';

// Group actions
export const GET_GROUPS_SUCCESS = 'GET_GROUPS_SUCCESS';
export const CREATE_GROUP_SUCCESS = 'CREATE_GROUP_SUCCESS';
export const GET_GROUP_MESSAGES_SUCCESS = 'GET_GROUP_MESSAGES_SUCCESS';
export const SEND_GROUP_MESSAGE_SUCCESS = 'SEND_GROUP_MESSAGE_SUCCESS';
export const GROUP_MESSAGE_SEND_SUCCESS_CLEAR = 'GROUP_MESSAGE_SEND_SUCCESS_CLEAR';

// Optional: If you use socket for group messages
export const SOCKET_GROUP_MESSAGE = 'SOCKET_GROUP_MESSAGE';

// Chatbot actions
export const FETCH_CHATBOT_MESSAGES = 'FETCH_CHATBOT_MESSAGES';
export const CHATBOT_MESSAGE_SEND_SUCCESS = 'CHATBOT_MESSAGE_SEND_SUCCESS';
export const CLEAR_CHATBOT_MESSAGES = 'CLEAR_CHATBOT_MESSAGES';
